services:
  - type: web
    name: lp-backend
    env: node
    rootDir: .
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20


